package com.player.management.pms.system;

public enum PmsServiceEnumStatus {

	SUCCESS,
	USER_ALREADY_EXISTS,
	USER_DETAILS_SAVED,
	EMAIL_ID_ALREADY_EXISTS,
	FAILURE,
	USER_NAME_AND_EMAIL_ID_ALREADY_EXISTS,
	EMAIL_ID_MATCH,
	PASSCODE_MATCH,
	PASSCODE_AND_EMAIL_ID_MATCHES,
	PASSCODE_AND_EMAIL_ID_MISMATCH,
	INVALID_LOGIN_CREDENTIAL,
	VALID_LOGIN,
	INVALID_DATA,
	USER_NAME_EXISTS,
	EMAIL_ID_EXISTS,
	PROFILE_SAVED
	
}
